#!/bin/bash -xe

# REQUEST_DELAY=0.5, works but SSSLLLLOOOOWWWW
# 0.0 is no good, 429 rate-limiting
REQUEST_DELAY=0.2
MAX_CONCURRENT=1

pkill -f "bfs-ql serve" || true

sleep 1

uv run bfs-ql serve --backend sparql --transport sse --port 8001 \
  --bif-contains --max-concurrent ${MAX_CONCURRENT} --request-delay ${REQUEST_DELAY} \
  --restrict-to-prefixes --log-level WARNING \
  --endpoint https://dbpedia.org/sparql \
  --prefix DBpedia=http://dbpedia.org/resource/ \
  --prefix DBpedia-owl=http://dbpedia.org/ontology/ \
  --exclude-predicate DBpedia-owl:wikiPageWikiLink \
  --exclude-predicate DBpedia-owl:wikiPageRedirects \
  --exclude-predicate "http://dbpedia.org/property/wikiPageUsesTemplate" \
  --description "DBpedia: open encyclopedia knowledge graph"
